from typing import Any

class Client:
    def __init__(self, api_key: str, api_secret: str, testnet: bool = ...) -> None: ...

    # Account & exchange info
    def get_account(self) -> dict[str, Any]: ...
    def get_exchange_info(self) -> dict[str, Any]: ...

    # Market data
    def get_symbol_ticker(self, *, symbol: str) -> dict[str, Any]: ...
    def get_klines(
        self, *, symbol: str, interval: str, limit: int
    ) -> list[list[Any]]: ...
    def get_ticker(self, *, symbol: str) -> dict[str, Any]: ...
    def get_all_tickers(self) -> list[dict[str, Any]]: ...
    def get_orderbook_ticker(self, *, symbol: str) -> dict[str, Any]: ...

    # Orders
    def get_all_orders(
        self, *, symbol: str, limit: int, orderId: int | None = ...
    ) -> list[dict[str, Any]]: ...
    def get_open_orders(self, *, symbol: str | None = ...) -> list[dict[str, Any]]: ...
    def create_order(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
    def cancel_order(
        self,
        *,
        symbol: str,
        orderId: int | None = ...,
        origClientOrderId: str | None = ...,
    ) -> dict[str, Any]: ...
    def cancel_all_open_orders(self, *, symbol: str) -> dict[str, Any]: ...
    def get_order(
        self,
        *,
        symbol: str,
        orderId: int | None = ...,
        origClientOrderId: str | None = ...,
    ) -> dict[str, Any]: ...
