from typing import Any

class DataFrame:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def set_index(self, *args: Any, **kwargs: Any) -> Any: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def __getitem__(self, key: Any) -> Any: ...

class Series:
    iloc: Any
    index: Any
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, key: Any) -> Any: ...

def to_numeric(arg: Any, *args: Any, **kwargs: Any) -> Any: ...
def to_datetime(arg: Any, *args: Any, **kwargs: Any) -> Any: ...
