from collections.abc import Callable
from typing import Any

class Job: ...

class AsyncIOScheduler:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add_job(self, func: Callable[..., Any], *args: Any, **kwargs: Any) -> Job: ...
    def start(self) -> None: ...
    def shutdown(self, wait: bool = ...) -> None: ...
